// Command gen_authzen_types emits this SDK's AuthZEN wire types from the
// language-neutral surface artifact published by the platform.
//
// # Why the types are generated rather than written
//
// The AuthZEN surface ships in five SDKs. Hand-transcribing the same twenty
// shapes five times produces five slightly different opinions about which
// fields are optional, and the resulting drift does not look like a bug: it
// looks like one SDK marking a field required that the others mark optional,
// discovered by a customer whose request is rejected by a server that another
// SDK talks to happily. The platform reduces its canonical JSON Schema to
// testdata/authzen-surface.json, every SDK generates from that one file, and
// each repository's CI regenerates and diffs.
//
// # The generated file is committed
//
// A consumer running `go get` must receive working types without running a
// generator, so the output is committed. A committed generated file is only
// worth anything if something proves it is the output of the current input,
// which authzen_types_gen_test.go does: it regenerates in memory and compares
// bytes, so editing either the artifact or the generated file without the other
// fails CI.
//
// Usage:
//
//	go run ./scripts/gen_authzen_types            # write authzen_types_gen.go
//	go run ./scripts/gen_authzen_types -check     # fail if it is out of date
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

const (
	surfacePath = "testdata/authzen-surface.json"
	outputPath  = "authzen_types_gen.go"
)

func main() {
	check := flag.Bool("check", false, "exit non-zero if the committed file is not what the artifact generates")
	flag.Parse()

	raw, err := os.ReadFile(surfacePath)
	if err != nil {
		fatalf("reading %s: %v", surfacePath, err)
	}
	surface, err := ParseSurface(raw)
	if err != nil {
		fatalf("%v", err)
	}
	src, err := Emit(surface)
	if err != nil {
		fatalf("%v", err)
	}

	if *check {
		have, err := os.ReadFile(outputPath)
		if err != nil {
			fatalf("-check: reading %s: %v", outputPath, err)
		}
		if !bytes.Equal(have, src) {
			fatalf("-check: %s is not what %s generates.\nRegenerate it in the same change:\n"+
				"  go run ./scripts/gen_authzen_types", outputPath, surfacePath)
		}
		return
	}
	if err := os.WriteFile(outputPath, src, 0o644); err != nil {
		fatalf("writing %s: %v", outputPath, err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen_authzen_types: "+format+"\n", args...)
	os.Exit(1)
}

// Emit renders the whole file.
func Emit(s *Surface) ([]byte, error) {
	if len(s.Types) == 0 || len(s.Enums) == 0 {
		return nil, fmt.Errorf("the artifact describes %d types and %d enums; "+
			"generating from an empty surface would silently produce an empty SDK",
			len(s.Types), len(s.Enums))
	}
	if s.Artifact != "axonflow-authzen-surface" {
		return nil, fmt.Errorf("%s is not an AuthZEN surface artifact (artifact=%q)", surfacePath, s.Artifact)
	}
	if s.ArtifactVersion != 1 {
		return nil, fmt.Errorf("artifact format version %d is not supported by this emitter; "+
			"a format change is a deliberate migration, not something to generate through",
			s.ArtifactVersion)
	}

	var b strings.Builder
	fmt.Fprintf(&b, `// Code generated by scripts/gen_authzen_types. DO NOT EDIT.
//
// Source: %s
//   artifact:        %s v%d
//   profile:         %s
//   contract schema: %s
//   schema digest:   %s
//
// Regenerate with:
//
//	go run ./scripts/gen_authzen_types
//
// Editing this file by hand is pointless: authzen_types_gen_test.go regenerates
// it in memory and compares bytes, so a hand edit fails CI on the next run.

package axonflow

`, surfacePath, s.Artifact, s.ArtifactVersion, s.Profile, s.ContractSchemaVersion, s.SourceSchemaSHA256)

	var body strings.Builder
	fmt.Fprintf(&body, `// AuthZENProfileV1 is the profile a Policy Enforcement Point negotiates to
// receive anything beyond the boolean decision.
//
// AuthZEN 1.0's response is a bare boolean. The four-valued state, the
// obligations, the approval challenge and the safe reason code all ride in the
// response context and are returned ONLY to a caller that asked for them by
// version, because handing a partial interpretation to a caller that cannot act
// on it is worse than handing it the boolean it understands.
const AuthZENProfileV1 = %q

// AuthZENContractSchemaVersion is the contract version these types were
// generated from. It is the value the server echoes in
// AuthZENResponseContext.SchemaVersion.
const AuthZENContractSchemaVersion = %q

`, s.Profile, s.ContractSchemaVersion)

	for _, e := range s.Enums {
		emitEnum(&body, e)
	}
	// Computed BEFORE emitting, because a type's validator calls its children's
	// and the children may be emitted after it.
	validated := computeValidated(s)
	for _, t := range s.Types {
		if err := emitType(&body, s, t, validated); err != nil {
			return nil, err
		}
	}

	// The import block is emitted only when the body needs it. Every generated
	// Validate uses fmt, and a surface with no exactly-one-of group and no
	// required fields would produce none - an unconditional import would then
	// be unused and the generated file would not compile. Deciding from the
	// rendered body rather than from a predicate keeps the two in step: a
	// future emitter that starts using fmt somewhere else does not also have to
	// remember to update a flag.
	if strings.Contains(body.String(), "fmt.") {
		b.WriteString("import \"fmt\"\n\n")
	}
	b.WriteString(body.String())

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("the generated source does not parse: %w", err)
	}
	return src, nil
}

func emitEnum(b *strings.Builder, e Enum) {
	name := goTypeName(e.Name)
	// Computed once and used by both sites below. Two spellings of the same
	// accessor name is one of them not compiling.
	all := "All" + pluralTypeName(name)
	fmt.Fprintf(b, "// %s is a closed set of values the server may send.\n", name)
	fmt.Fprintf(b, "//\n")
	fmt.Fprintf(b, "// It is a string type rather than an integer so an unrecognised value from a\n")
	fmt.Fprintf(b, "// newer server round-trips instead of decoding to a neighbouring constant.\n")
	fmt.Fprintf(b, "// Use Valid to tell a known value from one this build does not know.\n")
	fmt.Fprintf(b, "type %s string\n\nconst (\n", name)
	for _, v := range e.Values {
		fmt.Fprintf(b, "\t%s%s %s = %q\n", name, goConstSuffix(v), name, v)
	}
	fmt.Fprintf(b, ")\n\n")

	fmt.Fprintf(b, "// %s returns every value this build knows, in declaration order.\n", all)
	fmt.Fprintf(b, "func %s() []%s {\n\treturn []%s{\n", all, name, name)
	for _, v := range e.Values {
		fmt.Fprintf(b, "\t\t%s%s,\n", name, goConstSuffix(v))
	}
	fmt.Fprintf(b, "\t}\n}\n\n")

	fmt.Fprintf(b, "// Valid reports whether v is a value this build knows.\n")
	fmt.Fprintf(b, "//\n")
	fmt.Fprintf(b, "// A false result is not necessarily an error: a newer server may send a value\n")
	fmt.Fprintf(b, "// added after this SDK was built. It IS a reason not to branch on the value as\n")
	fmt.Fprintf(b, "// though it were one of the known ones.\n")
	fmt.Fprintf(b, "func (v %s) Valid() bool {\n\tfor _, known := range %s() {\n\t\tif known == v {\n\t\t\treturn true\n\t\t}\n\t}\n\treturn false\n}\n\n", name, all)
}

func emitType(b *strings.Builder, s *Surface, t Type, validated map[string]bool) error {
	name := goTypeName(t.Name)
	if t.Doc != "" {
		writeDoc(b, name+" is", t.Doc)
	} else {
		fmt.Fprintf(b, "// %s is part of the AuthZEN wire surface.\n", name)
	}
	fmt.Fprintf(b, "type %s struct {\n", name)
	for i, f := range t.Fields {
		if i > 0 {
			fmt.Fprintf(b, "\n")
		}
		if f.Doc != "" {
			writeFieldDoc(b, f.Doc)
		}
		if f.Const != "" {
			fmt.Fprintf(b, "\t// The only value the server sends is %q.\n", f.Const)
		}
		goType, err := goFieldType(s, f)
		if err != nil {
			return fmt.Errorf("%s.%s: %w", t.Name, f.Name, err)
		}
		tag := f.Name
		if !f.Required {
			tag += ",omitempty"
		}
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", goFieldName(f.Name), goType, tag)
	}
	fmt.Fprintf(b, "}\n\n")

	emitValidate(b, name, t, validated)
	return nil
}

// emitValidate renders the checks the type system cannot carry.
//
// Two constructs need it. The envelope's exactly-one-of rule cannot be a field
// tag, and the singular member's own required set is a property of the POSITION
// rather than of the referenced type. A generated struct without these compiles
// happily and builds requests the server refuses, which is the least useful
// place for a caller to find out.
func emitValidate(b *strings.Builder, name string, t Type, validated map[string]bool) {
	if !validated[t.Name] {
		return
	}

	fmt.Fprintf(b, "// Validate reports whether v carries what the server requires.\n")
	fmt.Fprintf(b, "//\n")
	fmt.Fprintf(b, "// Calling it is optional: the server enforces the same rules and answers with\n")
	fmt.Fprintf(b, "// a typed AuthZENError. It exists so a caller can fail before a round trip.\n")
	fmt.Fprintf(b, "func (v *%s) Validate() error {\n", name)
	fmt.Fprintf(b, "\tif v == nil {\n\t\treturn fmt.Errorf(\"%s: is nil\")\n\t}\n", name)

	for _, group := range t.ExactlyOneOf {
		var conds []string
		for _, m := range group {
			conds = append(conds, fmt.Sprintf("v.%s != nil", goFieldName(m)))
		}
		fmt.Fprintf(b, "\t{\n\t\tset := 0\n")
		for _, c := range conds {
			fmt.Fprintf(b, "\t\tif %s {\n\t\t\tset++\n\t\t}\n", c)
		}
		fmt.Fprintf(b, "\t\tif set != 1 {\n\t\t\treturn fmt.Errorf(\"%s: exactly one of %s must be set, %%d are\", set)\n\t\t}\n\t}\n",
			name, strings.Join(group, " or "))
	}

	for _, f := range t.Fields {
		fieldName := goFieldName(f.Name)
		if f.Required {
			switch f.Type.Kind {
			case "string", "enum":
				fmt.Fprintf(b, "\tif v.%s == \"\" {\n\t\treturn fmt.Errorf(\"%s: %s is required\")\n\t}\n", fieldName, name, f.Name)
			case "ref", "array", "map", "object":
				fmt.Fprintf(b, "\tif v.%s == nil {\n\t\treturn fmt.Errorf(\"%s: %s is required\")\n\t}\n", fieldName, name, f.Name)
			}
		}
		if f.MinItems > 0 {
			fmt.Fprintf(b, "\tif len(v.%s) < %d {\n\t\treturn fmt.Errorf(\"%s: %s needs at least %d entr%s\")\n\t}\n",
				fieldName, f.MinItems, name, f.Name, f.MinItems, plural(f.MinItems))
		}
		for _, m := range f.RequiresMembers {
			fmt.Fprintf(b, "\tif v.%s != nil && v.%s.%s == nil {\n\t\treturn fmt.Errorf(\"%s: %s has no %s; it has no shared base to inherit one from\")\n\t}\n",
				fieldName, fieldName, goFieldName(m), name, f.Name, m)
		}
		// NESTED validation. Without it a parent reports OK while a child
		// carries a violation the server refuses: an envelope naming a bulk
		// with zero entries passed here until this existed, because the entry
		// minimum lives on the bulk and nothing called it.
		switch f.Type.Kind {
		case "ref":
			if validated[f.Type.Ref] {
				fmt.Fprintf(b, "\tif v.%s != nil {\n\t\tif err := v.%s.Validate(); err != nil {\n\t\t\treturn fmt.Errorf(\"%s.%s: %%w\", err)\n\t\t}\n\t}\n",
					fieldName, fieldName, name, f.Name)
			}
		case "array":
			if f.Type.Items != nil && f.Type.Items.Kind == "ref" && validated[f.Type.Items.Ref] {
				fmt.Fprintf(b, "\tfor i := range v.%s {\n\t\tif err := v.%s[i].Validate(); err != nil {\n\t\t\treturn fmt.Errorf(\"%s.%s[%%d]: %%w\", i, err)\n\t\t}\n\t}\n",
					fieldName, fieldName, name, f.Name)
			}
		}
	}
	fmt.Fprintf(b, "\treturn nil\n}\n\n")
}

// computeValidated decides, for every type at once, which ones get a Validate.
//
// It is a FIXED POINT rather than a per-type predicate because the reasons
// compose: a type with no required member of its own still needs a Validate
// when it carries a member whose type has one. Without that step the local
// checks were asymmetric -- an envelope nil-checked its singular's subject and
// never called the subject's own validator, so a subject whose type was left at
// the Go zero value went out as "type": "" and came back as a refusal, which is
// precisely the round trip these validators exist to save.
//
// One map, computed before any emission, is also what keeps the two emission
// sites in step: a parent calling Validate on a child that has none does not
// compile, and a parent SKIPPING a child that has one is a validator that
// reports OK on a request the server refuses.
func computeValidated(s *Surface) map[string]bool {
	validated := map[string]bool{}
	for _, t := range s.Types {
		if typeHasOwnValidate(t) {
			validated[t.Name] = true
		}
	}
	for changed := true; changed; {
		changed = false
		for _, t := range s.Types {
			if validated[t.Name] {
				continue
			}
			for _, f := range t.Fields {
				if ref, ok := validatableRef(f.Type); ok && validated[ref] {
					validated[t.Name] = true
					changed = true
					break
				}
			}
		}
	}
	return validated
}

// validatableRef names the type a field would recurse into, for exactly the two
// shapes emitValidate knows how to emit a call for.
//
// Keeping this predicate and that emission in one correspondence is the point:
// a reason to have a Validate that the emitter cannot act on would produce a
// validator whose body checks nothing.
func validatableRef(tr TypeRef) (string, bool) {
	switch tr.Kind {
	case "ref":
		return tr.Ref, true
	case "array":
		if tr.Items != nil && tr.Items.Kind == "ref" {
			return tr.Items.Ref, true
		}
	}
	return "", false
}

// typeHasOwnValidate reports whether a type needs a Validate on its own account,
// before any member's type is considered.
func typeHasOwnValidate(t Type) bool {
	if len(t.ExactlyOneOf) > 0 || hasMemberRequirements(t) {
		return true
	}
	for _, f := range t.Fields {
		if f.Required {
			return true
		}
	}
	return false
}

func hasMemberRequirements(t Type) bool {
	for _, f := range t.Fields {
		if len(f.RequiresMembers) > 0 || f.MinItems > 0 {
			return true
		}
	}
	return false
}

func plural(n int) string {
	if n == 1 {
		return "y"
	}
	return "ies"
}

func goFieldType(s *Surface, f Field) (string, error) {
	return goType(s, f.Type, !f.Required)
}

func goType(s *Surface, tr TypeRef, optional bool) (string, error) {
	switch tr.Kind {
	case "string":
		return "string", nil
	case "bool":
		return "bool", nil
	case "int":
		return "int", nil
	case "object":
		return "map[string]any", nil
	case "enum":
		return goTypeName(tr.Enum), nil
	case "ref":
		// An optional struct is a pointer so "absent" and "present but zero"
		// stay distinguishable. Collapsing them is how an SDK reports that a
		// server sent an empty object when it sent nothing at all.
		if optional {
			return "*" + goTypeName(tr.Ref), nil
		}
		return goTypeName(tr.Ref), nil
	case "array":
		if tr.Items == nil {
			return "", fmt.Errorf("an array with no item type")
		}
		inner, err := goType(s, *tr.Items, false)
		if err != nil {
			return "", err
		}
		return "[]" + inner, nil
	case "map":
		if tr.Value == nil {
			return "", fmt.Errorf("a map with no value type")
		}
		inner, err := goType(s, *tr.Value, false)
		if err != nil {
			return "", err
		}
		return "map[string]" + inner, nil
	default:
		// Never a default type. An unrecognised kind silently rendered as
		// `any` would compile, ship, and accept values the server refuses.
		return "", fmt.Errorf("unsupported type kind %q", tr.Kind)
	}
}

// goTypeName maps an artifact name onto this SDK's exported name.
//
// Every generated type carries the AuthZEN prefix. It is not decoration: this
// package already declares Obligation (pep.go), and a generated type of the
// same name would not compile. Prefixing everything, rather than only what
// collides today, keeps the rule mechanical - a future collision does not
// require choosing a new convention under time pressure.
func goTypeName(artifactName string) string {
	return "AuthZEN" + pascal(strings.TrimPrefix(artifactName, "authzen_"))
}

// irregularPlurals covers the words the rules in pluralTypeName get wrong.
//
// Each entry is a word whose plural those rules would form regularly and
// incorrectly; anything they already handle stays out, because a table entry
// duplicating a rule is a second place to keep in step.
var irregularPlurals = map[string]string{
	"Index":     "Indices",
	"Vertex":    "Vertices",
	"Matrix":    "Matrices",
	"Criterion": "Criteria",
}

// pluralTypeName names the All<...> accessor for an enum type.
//
// The rule was name+"s", which produced AllAuthZENCategorys. That name is
// EXPORTED, so it is a compatibility commitment for as long as the surface
// lives, and the same emitter shape ships in four sibling SDKs -- the cheapest
// moment to be right about it is before any of them inherits it.
//
// The rules below the table are what stop this becoming a list somebody has to
// remember to extend: a later enum named authzen_severity pluralises correctly
// without an entry.
func pluralTypeName(name string) string {
	head, last := splitLastWord(name)
	if p, ok := irregularPlurals[last]; ok {
		return head + p
	}
	lower := strings.ToLower(last)
	switch {
	// A consonant before the y: Category -> Categories, but Key -> Keys.
	case len(lower) >= 2 && strings.HasSuffix(lower, "y") &&
		!strings.ContainsRune("aeiou", rune(lower[len(lower)-2])):
		return head + last[:len(last)-1] + "ies"
	case strings.HasSuffix(lower, "s"), strings.HasSuffix(lower, "x"), strings.HasSuffix(lower, "z"),
		strings.HasSuffix(lower, "ch"), strings.HasSuffix(lower, "sh"):
		return head + last + "es"
	default:
		return head + last + "s"
	}
}

// splitLastWord separates a PascalCase name's final word, which is the only one
// the plural applies to: AuthZENCategory pluralises Category, not AuthZEN.
func splitLastWord(name string) (head, last string) {
	for i := len(name) - 1; i > 0; i-- {
		if name[i] >= 'A' && name[i] <= 'Z' {
			return name[:i], name[i:]
		}
	}
	return "", name
}

func goFieldName(wire string) string {
	n := pascal(wire)
	// Go initialisms, so the generated names read like hand-written Go.
	for from, to := range map[string]string{"Id": "ID", "Url": "URL"} {
		if strings.HasSuffix(n, from) {
			n = strings.TrimSuffix(n, from) + to
		}
	}
	return n
}

func goConstSuffix(value string) string {
	// Enum values are either lower_snake ("not_permitted") or upper ("ALLOW").
	// Lowercasing first makes both paths go through one rule.
	return pascal(strings.ToLower(value))
}

func pascal(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '.' || r == '-' })
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}

// writeDoc renders the artifact's description as a Go doc comment.
func writeDoc(b *strings.Builder, lead, doc string) {
	lines := wrap(doc, 72)
	fmt.Fprintf(b, "// %s %s\n", lead, lines[0])
	for _, l := range lines[1:] {
		fmt.Fprintf(b, "// %s\n", l)
	}
}

func writeFieldDoc(b *strings.Builder, doc string) {
	for _, l := range wrap(doc, 68) {
		fmt.Fprintf(b, "\t// %s\n", l)
	}
}

// wrap reflows text to width, collapsing the artifact's newlines. The artifact
// carries prose wrapped for JSON, which is not where these end up.
func wrap(s string, width int) []string {
	words := strings.Fields(s)
	if len(words) == 0 {
		return []string{""}
	}
	var out []string
	cur := words[0]
	for _, w := range words[1:] {
		if len(cur)+1+len(w) > width {
			out = append(out, cur)
			cur = w
			continue
		}
		cur += " " + w
	}
	return append(out, cur)
}

// sortedTypeNames is used by the tests to assert coverage without depending on
// the artifact's own ordering.
func sortedTypeNames(s *Surface) []string {
	out := make([]string, 0, len(s.Types))
	for _, t := range s.Types {
		out = append(out, t.Name)
	}
	sort.Strings(out)
	return out
}
