// refresh_wire_shape_baseline regenerates testdata/wire_shape_baseline.json
// from a local checkout of getaxonflow/axonflow's docs/api/ directory.
//
// Usage:
//
//	go run ./scripts/refresh_wire_shape_baseline <specs_dir> [--sha <SHA>]
//
// When --sha is not provided, the script tries `git -C <specs_dir>
// rev-parse HEAD` to pick up the commit of the specs repo. If neither
// is available, the script exits non-zero rather than emit a poisoned
// baseline with an empty openapi_specs_sha — the next CI run would
// fail at workflow bootstrap anyway, so we fail fast here.
//
// All extraction logic is shared with contract_wire_shape_test.go via
// internal/wireshape so this tool and the gate cannot silently drift
// apart. The output file is written via temp-file + rename so a
// mid-encode failure never leaves a truncated baseline behind.

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/getaxonflow/axonflow-sdk-go/v8/internal/wireshape"
)

const baselineOut = "testdata/wire_shape_baseline.json"

func main() {
	shaFlag := flag.String("sha", "", "community-repo commit SHA to pin")
	flag.Parse()

	if flag.NArg() != 1 {
		fmt.Fprintln(os.Stderr, "usage: go run ./scripts/refresh_wire_shape_baseline <specs_dir> [--sha <SHA>]")
		os.Exit(2)
	}
	specsDir := flag.Arg(0)

	stat, err := os.Stat(specsDir)
	if err != nil || !stat.IsDir() {
		fmt.Fprintf(os.Stderr, "error: %s is not a directory\n", specsDir)
		os.Exit(2)
	}

	// Resolve SHA before any expensive work so a bad run terminates
	// early without touching the baseline file.
	sha := *shaFlag
	if sha == "" {
		sha = gitHeadSHA(specsDir)
	}
	if sha == "" {
		fmt.Fprintln(os.Stderr,
			"error: could not determine OpenAPI specs commit SHA.\n"+
				"  Either run this script against a specs_dir that sits inside a git\n"+
				"  checkout of the getaxonflow/axonflow community mirror, or pass\n"+
				"  --sha <commit-sha> explicitly. An empty SHA would poison\n"+
				"  testdata/wire_shape_baseline.json and break the next CI\n"+
				"  wire-shape-contract run at bootstrap.")
		os.Exit(2)
	}

	merged, crossSpecDuplicates, intraFileDuplicates, err := wireshape.LoadSchemas(specsDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	sdk, err := wireshape.DiscoverSDKTypes(".")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	registered := []string{}
	drift := map[string]wireshape.DriftEntry{}
	for name, sdkFields := range sdk {
		specFields, ok := merged[name]
		if !ok {
			continue
		}
		registered = append(registered, name)
		sdkOnly := wireshape.Difference(sdkFields, specFields)
		specOnly := wireshape.Difference(specFields, sdkFields)
		if len(sdkOnly) == 0 && len(specOnly) == 0 {
			continue
		}
		drift[name] = wireshape.DriftEntry{SDKOnly: sdkOnly, SpecOnly: specOnly}
	}
	sort.Strings(registered)

	out := wireshape.Baseline{
		Comment: "Baseline of KNOWN wire-shape drift between the Go SDK and the " +
			"OpenAPI specs. Generated by scripts/refresh_wire_shape_baseline. The CI " +
			"gate fails on drift OUTSIDE this baseline. Entries here should be burned " +
			"down over time via targeted fix PRs. See axonflow-enterprise tracking " +
			"issue (QF-11 follow-up).",
		OpenAPISpecsSHA:     sha,
		CrossSpecDuplicates: crossSpecDuplicates,
		IntraFileDuplicates: intraFileDuplicates,
		RegisteredTypes:     registered,
		PerTypeDrift:        drift,
	}

	if err := writeBaselineAtomically(baselineOut, &out); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Wrote baseline: %s\n", baselineOut)
	fmt.Printf("  openapi_specs_sha:     %s\n", sha)
	fmt.Printf("  cross_spec_duplicates: %d\n", len(crossSpecDuplicates))
	fmt.Printf("  intra_file_duplicates: %d files affected\n", len(intraFileDuplicates))
	fmt.Printf("  registered_types:      %d\n", len(registered))
	fmt.Printf("  per_type_drift:        %d\n", len(drift))
}

// writeBaselineAtomically writes b to path via a sibling temp file +
// rename, so a partial/interrupted encode cannot leave behind a
// truncated baseline that would fail the CI bootstrap step.
func writeBaselineAtomically(path string, b *wireshape.Baseline) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.CreateTemp(filepath.Dir(path), filepath.Base(path)+".tmp.*")
	if err != nil {
		return err
	}
	tmpPath := f.Name()
	cleanup := func() { _ = os.Remove(tmpPath) }
	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	if err := enc.Encode(b); err != nil {
		_ = f.Close()
		cleanup()
		return fmt.Errorf("encode baseline: %w", err)
	}
	if err := f.Close(); err != nil {
		cleanup()
		return fmt.Errorf("close temp file: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		cleanup()
		return fmt.Errorf("rename temp to %s: %w", path, err)
	}
	return nil
}

// gitHeadSHA reads the commit SHA of the git repo containing specDir,
// or returns "" if the path isn't a git checkout or git isn't on PATH.
// Best-effort: not a security boundary — the caller can always pass
// --sha explicitly.
func gitHeadSHA(specDir string) string {
	git, err := exec.LookPath("git")
	if err != nil {
		return ""
	}
	cmd := exec.Command(git, "-C", specDir, "rev-parse", "HEAD") //nolint:gosec // fixed args, caller-supplied dir
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}
