// refresh_wire_shape_baseline regenerates testdata/wire_shape_baseline.json
// from a specs directory: testdata/openapi (the derived snapshot) or a platform checkout's docs/api/.
//
// Usage:
//
//	go run ./scripts/refresh_wire_shape_baseline [--sha <SHA>] [--drop-notes] <specs_dir>
//
// (flags BEFORE the positional specs dir - the flag package stops
// parsing at the first non-flag argument.)
//
// For the snapshot, the pinned commit is the one its generated headers
// name, and a --sha that disagrees with them is refused. A directory
// without those headers (a platform checkout) needs --sha. There is no
// fallback to `git rev-parse HEAD`: inside this repository that names the
// SDK's own commit. Without a commit the script exits non-zero rather than
// emit a poisoned baseline with an empty openapi_specs_sha - the next CI
// run would fail at workflow bootstrap anyway, so we fail fast here.
//
// All extraction logic is shared with contract_wire_shape_test.go via
// internal/wireshape so this tool and the gate cannot silently drift
// apart. The output file is written via temp-file + rename so a
// mid-encode failure never leaves a truncated baseline behind.

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/getaxonflow/axonflow-sdk-go/v9/internal/wireshape"
)

const baselineOut = "testdata/wire_shape_baseline.json"

func main() {
	shaFlag := flag.String("sha", "", "platform commit the specs were taken from")
	dropNotes := flag.Bool("drop-notes", false,
		"confirm discarding curated _note keys that do not survive the regen")
	flag.Parse()

	if flag.NArg() != 1 {
		fmt.Fprintln(os.Stderr, "usage: go run ./scripts/refresh_wire_shape_baseline [--sha <SHA>] [--drop-notes] <specs_dir>")
		os.Exit(2)
	}
	if err := run(flag.Arg(0), *shaFlag, *dropNotes); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

// run regenerates the baseline at baselineOut (relative to the current
// working directory, like the SDK discovery itself). Split from main so
// the note-preservation contract is testable.
func run(specsDir, sha string, dropNotes bool) error {
	stat, err := os.Stat(specsDir)
	if err != nil || !stat.IsDir() {
		return fmt.Errorf("%s is not a directory", specsDir)
	}

	// Resolve SHA before any expensive work so a bad run terminates
	// early without touching the baseline file.
	sha, err = pinnedSHA(specsDir, sha)
	if err != nil {
		return err
	}

	merged, crossSpecDuplicates, intraFileDuplicates, err := wireshape.LoadSchemas(specsDir)
	if err != nil {
		return err
	}
	sdk, err := wireshape.DiscoverSDKTypes(".")
	if err != nil {
		return err
	}

	registered := []string{}
	drift := map[string]wireshape.DriftEntry{}
	for name, sdkFields := range sdk {
		specFields, ok := merged[name]
		if !ok {
			continue
		}
		registered = append(registered, name)
		sdkOnly := wireshape.Difference(sdkFields, specFields)
		specOnly := wireshape.Difference(specFields, sdkFields)
		if len(sdkOnly) == 0 && len(specOnly) == 0 {
			continue
		}
		drift[name] = wireshape.DriftEntry{SDKOnly: sdkOnly, SpecOnly: specOnly}
	}
	sort.Strings(registered)

	// Preserve the curated _note keys from the existing baseline: they
	// are the paper trail (tracking issue + burn-down condition) that
	// authorizes each drift entry, and a regen must not silently drop
	// them. Vanished-type acknowledgment entries (empty except for a
	// _note, type still unmapped) are preserved wholesale. Any note
	// that would not survive is listed and blocks the regen unless
	// --drop-notes confirms the discard.
	prev, prevErr := readExistingBaseline(baselineOut)
	if prevErr != nil && !os.IsNotExist(prevErr) {
		// A corrupt or unreadable previous baseline must not silently
		// become "no previous baseline" - that path discards every
		// curated note while exiting 0.
		return fmt.Errorf("previous baseline %s exists but cannot be used: %w", baselineOut, prevErr)
	}
	if prev != nil {
		dropped := wireshape.CarryDriftNotes(prev.PerTypeDrift, drift, sdk, merged)
		if len(dropped) > 0 {
			fmt.Fprintf(os.Stderr, "dropped %d curated note(s):\n", len(dropped))
			for _, d := range dropped {
				fmt.Fprintf(os.Stderr, "  - %s\n", d)
			}
			if !dropNotes {
				return fmt.Errorf(
					"regen would drop %d curated _note key(s) (listed above). "+
						"If the drop is intentional (entry burned down, type renamed), "+
						"re-run with --drop-notes; otherwise move each note to the "+
						"surviving entry name first", len(dropped))
			}
		}
	}

	out := wireshape.Baseline{
		Comment: "Baseline of KNOWN wire-shape drift between the Go SDK and the " +
			"OpenAPI specs. Generated by scripts/refresh_wire_shape_baseline. The CI " +
			"gate fails on drift OUTSIDE this baseline. Entries here should be burned " +
			"down over time via targeted fix PRs. See axonflow-enterprise tracking " +
			"issue (QF-11 follow-up).",
		OpenAPISpecsSHA:     sha,
		CrossSpecDuplicates: crossSpecDuplicates,
		IntraFileDuplicates: intraFileDuplicates,
		RegisteredTypes:     registered,
		PerTypeDrift:        drift,
	}

	if err := writeBaselineAtomically(baselineOut, &out); err != nil {
		return err
	}

	fmt.Printf("Wrote baseline: %s\n", baselineOut)
	fmt.Printf("  openapi_specs_sha:     %s\n", sha)
	fmt.Printf("  cross_spec_duplicates: %d\n", len(crossSpecDuplicates))
	fmt.Printf("  intra_file_duplicates: %d files affected\n", len(intraFileDuplicates))
	fmt.Printf("  registered_types:      %d\n", len(registered))
	fmt.Printf("  per_type_drift:        %d\n", len(drift))
	return nil
}

// readExistingBaseline loads the baseline currently on disk, if any.
// Any read or parse failure is reported to the caller, which treats it
// as "no previous baseline" (a bootstrap run has nothing to preserve).
func readExistingBaseline(path string) (*wireshape.Baseline, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var b wireshape.Baseline
	if err := json.Unmarshal(data, &b); err != nil {
		return nil, err
	}
	if b.PerTypeDrift == nil {
		b.PerTypeDrift = map[string]wireshape.DriftEntry{}
	}
	return &b, nil
}

// writeBaselineAtomically writes b to path via a sibling temp file +
// rename, so a partial/interrupted encode cannot leave behind a
// truncated baseline that would fail the CI bootstrap step.
func writeBaselineAtomically(path string, b *wireshape.Baseline) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.CreateTemp(filepath.Dir(path), filepath.Base(path)+".tmp.*")
	if err != nil {
		return err
	}
	tmpPath := f.Name()
	cleanup := func() { _ = os.Remove(tmpPath) }
	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	if err := enc.Encode(b); err != nil {
		_ = f.Close()
		cleanup()
		return fmt.Errorf("encode baseline: %w", err)
	}
	if err := f.Close(); err != nil {
		cleanup()
		return fmt.Errorf("close temp file: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		cleanup()
		return fmt.Errorf("rename temp to %s: %w", path, err)
	}
	return nil
}

// pinnedSHA returns the platform commit to record as openapi_specs_sha.
// For a generated snapshot it is the commit the snapshot's headers name,
// and an explicit --sha that disagrees is refused. A directory without
// those headers (a platform checkout of docs/api) needs --sha. There is no
// fallback to `git rev-parse HEAD`: testdata/openapi sits inside this
// repository, so HEAD would name the SDK's own commit.
func pinnedSHA(specsDir, explicitSHA string) (string, error) {
	headerSHA, err := wireshape.SnapshotSourceCommit(specsDir)
	if err != nil {
		return "", err
	}
	explicitSHA = strings.TrimSpace(explicitSHA)
	if headerSHA == "" {
		if explicitSHA == "" {
			return "", fmt.Errorf(
				"%s is not a generated snapshot (no file carries the header naming\n"+
					"  its platform commit), so pass --sha <commit-sha> for the platform\n"+
					"  checkout it came from. An empty SHA would poison\n"+
					"  testdata/wire_shape_baseline.json and break the next CI\n"+
					"  wire-shape-contract run at bootstrap", specsDir)
		}
		return explicitSHA, nil
	}
	if explicitSHA != "" && explicitSHA != headerSHA {
		return "", fmt.Errorf(
			"--sha %s disagrees with the snapshot in %s, whose generated headers\n"+
				"  name platform commit %s. The baseline must pin the revision the\n"+
				"  snapshot holds: regenerate the snapshot at the commit you mean, or\n"+
				"  drop --sha", explicitSHA, specsDir, headerSHA)
	}
	return headerSHA, nil
}
